name: Mirror to Bitbucket
on: [push]
jobs:
  mirror-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # <-- clone with complete history
    - name: Push
      uses: heussd/mirror-to-bitbucket-github-action@v2
      with:
        password: ATBBnK8J9pKA28q6NhVGmzzRrtjT1AC54F63
        spacename: Neuralab
